name: Github Page Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Transfer build files to server
        uses: appleboy/scp-action@v0.0.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "build/*"
          target: "/home/ubuntu/front/GalleryFront/build"
          strip_components: 1